name: C/C++ CI

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: cd mpy-cross;make;cd ../ports/unix;make submodules;make
      
  windows:      
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: |
        cd mpy-cross
        msbuild mpy-cross.vcxproj /property:Platform=x86
        
    
