name: C/C++ CI

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: cd mpy-cross;make;cd ../ports/unix;make submodules;make
      
  windows:      
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: |
        cd mpy-cross
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" mpy-cross.vcxproj /property:Platform=x86
        cd ../ports/windows
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" micropython.vcxproj /property:Platform=x86
      shell: cmd
    
    
